# Site settings
title: "Roberto De Simone"
email: "robertodesimone1998@gmail.com"
description: > # this means to ignore newlines until "baseurl:"
baseurl: "https://robertodesimone98.github.io/" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

ig_username: "roberto.koi_"
linkedin_username: "roberto-desimone"

# Build settings
markdown: kramdown

collections:
  projects:
    output: true